apiVersion: apps/v1
kind: Deployment
metadata:
  name: pregnant-pills-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pregnant-pills
      env: dev
  template:
    metadata:
      labels:
        app: pregnant-pills
        env: dev
    spec:
      containers:
        - name: pregnant-pills-container
          image: rockpiryt/pregnant-pills:latest
          env:
          - name: DATABASE_URL
            value: "sqlite:////app/data/app.db"
          volumeMounts:
          - name: sqlite-db-persitent
            mountPath: /app/data
      volumes:
      - name: sqlite-db-persitent
        persistentVolumeClaim:
            claimName: sqlite-pvc