apiVersion: v1
kind: Service
metadata:
  name: pregnant-pills-service
spec:
  selector:
    app: pregnant-pills
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
