apiVersion: v1
kind: Service
metadata:
  name: preg-memo-svc
spec:
  selector:
    app: preg-memo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
