apiVersion: v1
kind: Secret
metadata:
  name: preg-app-secrets
type: Opaque
stringData:
  SECRET_KEY: "change-me"
  DATABASE_URL: "postgresql://preguser:password@preg-postgres.xxx.eu-west-1.rds.amazonaws.com:5432/pregdb"
