apiVersion: v1
kind: Service
metadata:
  name: preg-pills-nd-svc-prod
  labels:
    app: preg-pills
spec:
  type: NodePort
  selector:
    app: preg-pills # przypisanie svc do deploy
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
