apiVersion: apps/v1
kind: Deployment
metadata:
  name: pregnant-pills-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pregnant-pills
  template:
    metadata:
      labels:
        app: pregnant-pills
    spec:
      containers:
        - name: pregnant-pills-container
          image: rockpiryt/pregnant-pills:prod

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

          ports:
            - name: http
              containerPort: 8080

          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: pregnant-pills-config
                  key: APP_ENV

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: pregnant-pills-secrets
                  key: SECRET_KEY

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pregnant-pills-secrets
                  key: DATABASE_URL

