apiVersion: v1
kind: Service
metadata:
  name: pregnant-pills-nodeport-svc-prod
  labels:
    app: preg-pills
spec:
  type: NodePort
  selector:
    app: app-preg-pills-prod # przypisanie svc do deploy
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
